---
- hosts: servers_all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: sundar
  sudo: yes
  tasks:
  - name: Install apache package
    apt: name={{ item }} state=latest
    with_items: 
     - apache2
     - apache2-doc
#  - name: check config file
#    shell: "cp -p /usr/share/doc/apache2-doc/examples/apache2/original/httpd.conf.gz /etc/httpd.conf.gz"
#  - name: extract conf files
#    shell: "gunzip -f /etc/httpd.conf.gz"
#    notify: 
#     - restart apache
  - name: create document root
    file: path=/www state=directory
  - name: copy home page
    template: src=/root/playbooks/index.html dest=/www/ mode=644 owner=root group=root
  - name: allow access to site
    template: 
       src: /root/playbooks/apache2.conf
       dest: /etc/apache2/apache2.conf
       backup: yes
       owner: root
       group: root
       mode: "0644"
    notify: restart apache
  - name: edit document root
    lineinfile: 
       name: /etc/apache2/sites-available/000-default.conf
       regexp: 'DocumentRoot'
       line: 'DocumentRoot "/www"'
       backup: yes
    notify: restart apache
  - name: ensure apache is running and enabled
    service: name=apache2 state=started enabled=yes
  handlers:
   - name: restart apache
     service: name=apache2 state=restarted
...
